/**
 * Loop contract — core types for the Briefings v2 "loop of loops" system.
 *
 * NORMATIVE SOURCE: docs/plans/briefings-v2-loop-of-loops.html (§3 ontology & contract, §5 homes,
 * §6 verdict & feedback). This file is the ontology made executable; if it disagrees with the
 * scope, the scope wins and this file gets fixed.
 *
 * The shape in one breath: every loop emits ITEMS (insight | action | proposal). Escalation is an
 * URGENCY PROPERTY any item can carry (top-fold today), orthogonal to whether the item ASKS for a
 * verdict (only actions/proposals do). Loops write dated markdown ARTIFACTS — frontmatter carries
 * the structured data (items, health) so machines can act; body sections carry the human prose.
 * Justin responds through two channels: FEEDBACK (free-form, attaches to anything, consumed by the
 * loop's next health pass) and VERDICTS (enumerated, asks only, executed mechanically, counted).
 * Markdown remains the source of truth (Hilt constraint) — everything here round-trips through
 * files under bridge/meta/loops/<domain>/.
 */

// ── Items (scope §3.1) ────────────────────────────────────────────────────────────────────────

export type ItemKind = "insight" | "action" | "proposal";

export type Verdict = "approve" | "dismiss" | "assign_to_me" | "assign_to_agent" | "revise";

/** Provenance — every item cites where it came from. The citation doubles as the feedback anchor
 *  for content items (scope §6: anchor = loop + section + citation + text; validated in the
 *  launchpad before we resort to minting ids for every content bullet). */
export interface Citation {
  /** Vault-relative path, e.g. "meetings/2026-07-01/seb-1on1.md". */
  source: string;
  /** ISO date of the source material (not the run). */
  date?: string;
  /** Line anchor or short quoted span locating the evidence inside the source. */
  anchor?: string;
}

/**
 * A single emitted item. `id` is minted by the emitting loop and STABLE across runs — the same
 * commitment re-observed tomorrow keeps its id (identity is the ledger's hard problem, scope §9.1).
 * For asks (action | proposal), the id is also the verdict-log join key.
 */
export interface LoopItem {
  id: string;
  loop: string;
  kind: ItemKind;
  /** One-line headline (the briefing bullet). */
  title: string;
  /** Optional detail body (sub-bullet material), markdown. */
  detail?: string;
  citations: Citation[];
  /** Urgency property — "top fold today". Orthogonal to ask-ness (an escalated insight takes no
   *  verdict; an un-escalated action still wants one eventually). */
  escalated?: { reason: string };
  /** Extractor/loop confidence 0..1 — asks only; drives review priority. Catch-phrase captures
   *  are high-confidence by construction (scope: "Action item:" trigger). */
  confidence?: number;
  /** Owner of the work an action proposes. Kept open to agent values for v1.5+ (scope: deferred). */
  owner?: string;
  /** Allowed verdicts for asks. Omitted for insights. Loops may narrow (e.g. proposals don't
   *  offer assign_*), never widen beyond the Verdict union. */
  allowed_verdicts?: Verdict[];
}

// ── Loop health (scope §3.2 — the REQUIRED self-eval dimension) ──────────────────────────────

export interface LoopHealth {
  ok: boolean;
  /** Run metrics — attempted/succeeded/coverage, loop-defined semantics but always numeric. */
  attempted?: number;
  succeeded?: number;
  /** 0..1 — how much of the loop's domain this run actually covered. */
  coverage?: number;
  /** Quality self-eval + drift vs. recent runs, prose. */
  quality_notes?: string;
  /** Ids of tuning `proposal` items emitted this run (they live in `items` like everything else). */
  proposal_ids?: string[];
  /** Operational notes — anything the runtime loop or a human debugger should see. */
  notes?: string;
}

// ── Artifact (scope §3.2) ─────────────────────────────────────────────────────────────────────

/**
 * Frontmatter of a dated loop artifact at meta/loops/<domain>/reports/YYYY-MM-DD.md.
 * The body renders the human sections (content sections loop-defined; ## Escalations is a VIEW of
 * items where escalated is set; ## Loop health mirrors `health`). Machines read the frontmatter;
 * humans read the body; the two are written together by the same run and must agree.
 */
export interface LoopArtifactFrontmatter {
  loop: string;
  /** ISO timestamp of the run that wrote this artifact. */
  run_at: string;
  cadence: LoopCadence;
  /** Present when generated by the launchpad: the historical "as of" date the run was bounded to.
   *  Artifacts with as_of set are sandbox-only by definition. */
  as_of?: string;
  /** All items emitted this run (escalated ones are ALSO rendered in the ## Escalations body
   *  section; that section is a view, not a store). */
  items: LoopItem[];
  health: LoopHealth;
}

// ── Registry (scope §5) ───────────────────────────────────────────────────────────────────────

export type LoopCadence = "daily" | "weekly" | "manual";

/** Rollout state — the write guard's input. A loop's runner REFUSES writes outside the sandbox
 *  unless the registry says "live" (implementation plan §1.4 / risk #3). */
export type LoopPhase = "shadow" | "live";

export interface RegistryLoop {
  /** Loop id, e.g. "meeting-actions". */
  id: string;
  /** Root content domain it mirrors, e.g. "meetings" → meta/loops/meetings/. The runtime loop
   *  uses "system" (no root mirror — its domain IS the machine). */
  domain: string;
  cadence: LoopCadence;
  enabled: boolean;
  phase: LoopPhase;
  /** Human-facing surfaces this loop publishes to (documentation for the inventory; the briefing
   *  reads artifacts regardless). */
  published_surfaces?: string[];
  /** Which loop writes this domain's artifacts when it isn't the domain's own loop — e.g. the
   *  people projections are written by meeting-actions ("home follows domain, not generator"). */
  writer?: string;
  /** Where the loop's escalation-time task PROPOSALS land (v3 unit A6). `"vault"` = the vault's
   *  canonical `tasks/.proposals/` — the auditable graduation of just this one write. Absent =
   *  shadow default (`<loopHome>/proposals/`). CLI flags (`--proposals-dir`, `--ledger-home`)
   *  override the registry; see resolveProposalSink in proposal-mint.ts. */
  proposal_sink?: "vault";
  /** Adaptive budget envelope, recorded per interview decision: model tier + rough token/wall
   *  expectations, tuned during the launchpad. Advisory, not enforced. */
  budget?: { model?: string; notes?: string };
}

export interface LoopsRegistry {
  loops: RegistryLoop[];
}

// ── Responses: feedback & verdicts (scope §6) ────────────────────────────────────────────────

export type ResponseAuthor = "justin" | "claude-sim";

/** Where a piece of feedback attaches. Exactly one of `item_id` or `anchor` for item-level
 *  feedback; section/briefing-level feedback sets `level` accordingly and omits both. */
export interface FeedbackTarget {
  loop: string;
  /** Artifact date the feedback was given against (YYYY-MM-DD), when applicable. */
  artifact_date?: string;
  level: "item" | "section" | "briefing";
  /** For asks and any item with a minted id. */
  item_id?: string;
  /** For synthesized content bullets without ids: citation-based anchor (scope §6). */
  anchor?: { section?: string; citation?: string; text: string };
}

export interface FeedbackRecord {
  id: string;
  author: ResponseAuthor;
  created_at: string;
  target: FeedbackTarget;
  /** The critique itself, free-form. */
  text: string;
  /** Stamped by the owning loop's health pass when consumed. Unprocessed = pending input. */
  processed?: { at: string; run_at: string };
}

export interface VerdictRecord {
  id: string;
  author: ResponseAuthor;
  created_at: string;
  loop: string;
  /** The ask being decided (LoopItem.id of an action | proposal). */
  item_id: string;
  verdict: Verdict;
  /** Free-form note — required for "revise" (the note IS the revision guidance; scope: the revise
   *  is a verdict, the note is feedback embedded in it). */
  note?: string;
  /** Stamped by the loop when it acts on the verdict on its next run. */
  acted?: { at: string; run_at: string };
}

// ── Surfacing state (scope §6 — escalation dedupe memory, owned by the briefing loop) ───────

export interface SurfacedItemState {
  first_surfaced: string;
  last_surfaced: string;
  times_surfaced: number;
  /** Set when a verdict lands; default rendering = suppressed thereafter. The model keeps
   *  editorial latitude to override (resurface/expand) but overrides must be VISIBLE in the
   *  briefing (interview decision + guardrail). */
  verdict?: Verdict;
}

/** item_id (or stable anchor hash for id-less content) → state. Lives at
 *  meta/loops/briefings/state/surfacing.json. */
export type SurfacingState = Record<string, SurfacedItemState>;
