import { test } from "node:test";
import assert from "node:assert/strict";
import {
  cleanLoopTokens,
  extractMeetingRelPath,
  extractTaskIds,
  isNextStepsHeading,
  isRedundantMeetingCitationLine,
  isTaskIdOnlyLine,
  meetingLabelFromRelPath,
  parseBriefing,
  stripTaskTokens,
  normalizeHiltLinks,
} from "./canvas";

// ── parseBriefing (moved out of BriefingContent at B3 — behavior locked here) ─────────────────

const SAMPLE = `# Morning Briefing — Tuesday, July 7, 2026

**The day-thesis lede.**

## 📅 Today

- Survey cadence UX, **10:00AM**

## ⏭ Next steps

- **OC planning (6/30)** — Phase 2 verbally approved; outline is the deliverable
  - *meetings/2026-06-30/Owens Corning (Just Keep Swimming)-2026-06-30 @ 14-00-25.md, 2026-06-30*
  - \`t-20260707-011\`
  - \`t-20260707-012\`

## 📚 Library & knowledge

Prose paragraph line.

[Full library report](/api/reports/morning)

---
*Generated by the \`briefing\` skill.*
`;

test("parseBriefing: lede, sections, bullets, details, prose items, footer stop", () => {
  const { lede, sections } = parseBriefing(SAMPLE);
  assert.equal(lede, "**The day-thesis lede.**");
  assert.deepEqual(sections.map((s) => s.heading), ["📅 Today", "⏭ Next steps", "📚 Library & knowledge"]);
  const next = sections[1];
  assert.equal(next.items.length, 1);
  assert.ok(next.items[0].headline.startsWith("**OC planning"));
  assert.ok(next.items[0].details.includes("t-20260707-011"));
  assert.ok(next.items[0].details.includes("meetings/2026-06-30/"));
  const lib = sections[2];
  assert.equal(lib.items[0].prose, true, "paragraph lines are preserved as prose items");
  assert.ok(!JSON.stringify(sections).includes("Generated by"), "footer is cut at the hrule");
});

// ── task-id contract ──────────────────────────────────────────────────────────────────────────

test("extractTaskIds: backticked + bare, unique, in order; never matches loop item ids", () => {
  assert.deepEqual(
    extractTaskIds("do it `t-20260707-004` and t-20260707-009 then `t-20260707-004` again"),
    ["t-20260707-004", "t-20260707-009"],
  );
  assert.deepEqual(extractTaskIds("*loop:meeting-actions, ma-2026-06-30-007*"), []);
  assert.deepEqual(extractTaskIds("t-2026-07-07-001 is a loop-shaped id, not a task id"), []);
  assert.deepEqual(extractTaskIds("no ids here"), []);
});

test("stripTaskTokens removes ids and the artifact's arrow remnant, keeps prose", () => {
  assert.equal(
    stripTaskTokens("Confirm ASM titles `ma-x` → task `t-20260707-011` today").replace(/ +/g, " ").trim(),
    "Confirm ASM titles `ma-x` today",
  );
  assert.equal(stripTaskTokens("- `t-20260707-011`").trim(), "-");
  assert.equal(stripTaskTokens("plain prose stays"), "plain prose stays");
});

test("stripTaskTokens never eats loop item ids (disjoint shapes)", () => {
  const line = "see *loop:meeting-actions, ma-2026-06-30-007* and `t-20260707-001`";
  const stripped = stripTaskTokens(line);
  assert.ok(stripped.includes("ma-2026-06-30-007"));
  assert.ok(!stripped.includes("t-20260707-001"));
  // and the pre-existing loop cleaner never eats task ids
  const cleaned = cleanLoopTokens(line);
  assert.ok(cleaned.includes("t-20260707-001"));
  assert.ok(!cleaned.includes("ma-2026-06-30-007"));
});

test("isTaskIdOnlyLine: id-only sub-bullets are consumed; prose lines are not", () => {
  assert.equal(isTaskIdOnlyLine("  - `t-20260707-011`"), true);
  assert.equal(isTaskIdOnlyLine("- t-20260707-011"), true);
  assert.equal(isTaskIdOnlyLine("  - `t-20260707-011` *meetings/2026-06-30/OC.md, 2026-06-30*"), true);
  assert.equal(isTaskIdOnlyLine("  - Confirm ASM titles `t-20260707-011`"), false);
  assert.equal(isTaskIdOnlyLine("  - plain sub-bullet, no id"), false);
  assert.equal(isTaskIdOnlyLine(""), false);
});

// ── meeting citations ─────────────────────────────────────────────────────────────────────────

test("extractMeetingRelPath handles spaces/@/unicode filenames and citation wrappers", () => {
  const citation = "  - *meetings/2026-06-30/Owens Corning (Just Keep Swimming)-2026-06-30 @ 14-00-25.md, 2026-06-30*";
  assert.equal(
    extractMeetingRelPath(citation),
    "meetings/2026-06-30/Owens Corning (Just Keep Swimming)-2026-06-30 @ 14-00-25.md",
  );
  const emoji = "*meetings/2026-07-06/📐 Insights Architecture-2026-07-06 @ 11-01-51.md, 2026-07-06*";
  assert.equal(extractMeetingRelPath(emoji), "meetings/2026-07-06/📐 Insights Architecture-2026-07-06 @ 11-01-51.md");
  assert.equal(extractMeetingRelPath("no meeting cited"), null);
});

test("isRedundantMeetingCitationLine: suppresses ONLY the card's own bare citation", () => {
  const rel = "meetings/2026-07-06/Justin__Jason 1_1-2026-07-06 @ 13-00-34.md";
  // The canonical SKILL citation form for the card's own meeting — redundant, suppressed.
  assert.equal(
    isRedundantMeetingCitationLine(`  - *${rel}, 2026-07-06*`, rel),
    true,
  );
  assert.equal(isRedundantMeetingCitationLine(`- *${rel}*`, rel), true);
  // Same citation but for a DIFFERENT meeting's card — different source, keep.
  assert.equal(
    isRedundantMeetingCitationLine(`  - *${rel}, 2026-07-06*`, "meetings/2026-06-30/Owens Corning (Just Keep Swimming)-2026-06-30 @ 14-00-25.md"),
    false,
  );
  // Citation with an ADDITIONAL source in the same span — adds information, keep.
  assert.equal(
    isRedundantMeetingCitationLine(`  - *${rel}, 2026-07-06; lists/now/2026-06-29.md*`, rel),
    false,
  );
  // Real prose alongside the citation — keep.
  assert.equal(
    isRedundantMeetingCitationLine(`  - Alamo trend context. *${rel}, 2026-07-06*`, rel),
    false,
  );
  // No meeting citation at all — not this rule's business.
  assert.equal(isRedundantMeetingCitationLine("  - plain sub-bullet", rel), false);
  assert.equal(isRedundantMeetingCitationLine("  - *lists/now/2026-06-29.md*", rel), false);
});

test("meetingLabelFromRelPath derives title + date", () => {
  assert.deepEqual(
    meetingLabelFromRelPath("meetings/2026-06-30/Owens Corning (Just Keep Swimming)-2026-06-30 @ 14-00-25.md"),
    { title: "Owens Corning (Just Keep Swimming)", date: "2026-06-30" },
  );
});

// ── section marker ────────────────────────────────────────────────────────────────────────────

test("isNextStepsHeading keys on the ⏭ marker (incl. VS16), never on the words alone", () => {
  assert.equal(isNextStepsHeading("⏭ Next steps"), true);
  assert.equal(isNextStepsHeading("⏭️ Next steps"), true);
  assert.equal(isNextStepsHeading("🧠 Don't drop this"), false);
  // an old briefing mentioning "next steps" in a heading must NOT trigger the canvas treatment
  assert.equal(isNextStepsHeading("Next steps"), false);
});

test("normalizeHiltLinks: bare space/paren destinations become angle-bracket form; clean forms untouched", () => {
  const bare = "- **[Survey UX](hilt:meeting/meetings/2026-07-07/Discuss survey cadence UX-2026-07-07 @ 09-57-15.md) (7/7)** — lead";
  const fixed = normalizeHiltLinks(bare);
  assert.ok(fixed.includes("](<hilt:meeting/meetings/2026-07-07/Discuss survey cadence UX-2026-07-07 @ 09-57-15.md>)"));
  const parens = "[OC](hilt:meeting/meetings/2026-06-30/Owens Corning (Just Keep Swimming)-2026-06-30 @ 14-00-25.md)";
  assert.ok(normalizeHiltLinks(parens).includes("(Just Keep Swimming)-2026-06-30 @ 14-00-25.md>)"));
  const already = "[x](<hilt:meeting/meetings/2026-07-07/a b.md>)";
  assert.equal(normalizeHiltLinks(already), already);
  const task = "[t](hilt:task/t-20260707-001)";
  assert.equal(normalizeHiltLinks(task), task);
});
