import assert from "node:assert/strict";
import test from "node:test";
import { appendDecisionQueueMarkdown } from "./decision-append";
import { DECISION_CONTRACT_MARKER, type BriefingDecisionQueue } from "./decisions";

const BASE = `# Briefing

## 🧠 Don't drop this

- Keep moving

## ⏭ Decisions awaiting you

- The first meeting settled the implementation direction but left ownership unresolved.
  - *meetings/2026-07-10/One.md, 2026-07-10*
  - \`t-20260710-001\`

## 💼 Work & product

- Project moved

---
*Generated by the briefing skill.*
${DECISION_CONTRACT_MARKER}
`;

const queue: BriefingDecisionQueue = {
  as_of: "2026-07-11",
  artifact_date: "2026-07-11",
  warnings: [],
  task_ids: ["t-20260711-002", "t-20260711-003"],
  groups: [
    {
      meeting: "meetings/2026-07-10/One.md",
      title: "One",
      date: "2026-07-10",
      urgent: false,
      tasks: [{ id: "t-20260711-002", title: "Added to one", meeting: "meetings/2026-07-10/One.md", created_at: "2026-07-11T08:00:00Z", urgent: false }],
    },
    {
      meeting: "meetings/2026-07-11/Two.md",
      title: "Two",
      date: "2026-07-11",
      summary: "A second meeting introduced an approval that now gates the next delivery step.",
      urgent: true,
      tasks: [{ id: "t-20260711-003", title: "New meeting decision", meeting: "meetings/2026-07-11/Two.md", created_at: "2026-07-11T09:00:00Z", urgent: true }],
    },
  ],
};

test("same-day append preserves frozen ids and editorial context while adding canonical proposals", () => {
  const result = appendDecisionQueueMarkdown(BASE, "daily", queue);
  assert.equal(result.added, 2);
  assert.match(result.markdown, /The first meeting settled the implementation direction/);
  assert.match(result.markdown, /A second meeting introduced an approval/);
  assert.match(result.markdown, /`t-20260710-001`/);
  assert.match(result.markdown, /`t-20260711-002`/);
  assert.match(result.markdown, /`t-20260711-003`/);
  assert.doesNotMatch(result.markdown, /decisions? across/i);
  assert.doesNotMatch(result.markdown, /New meeting decision/);
});

test("legacy briefings are never rewritten", () => {
  const legacy = BASE.replace(DECISION_CONTRACT_MARKER, "");
  assert.deepEqual(appendDecisionQueueMarkdown(legacy, "daily", queue), { markdown: legacy, added: 0 });
});
