import type { BriefingMode } from "./target-file";
import { extractRecommendationEpisodeIds, extractTaskIds, isDecisionsHeading, isRecommendationEpisodeOnlyLine, isRedundantMeetingCitationLine, isTaskIdOnlyLine } from "./canvas";
import { decisionContextEchoesTaskTitle } from "./decisions";

/**
 * Structural gate for a generated briefing — the deterministic half of "verified parity". Encodes the
 * contract derived from SKILL.md + the real Hermes gold briefings (and the two findings from the
 * parity-verification workflow: the gold daily band is ~4.0–4.5KB, NOT the 1.6–2.5KB first guessed;
 * and a fresh editor's-memo headline MUST carry the [Read the memo] link — that was the one miss).
 *
 * `failures` are hard (block publish); `warnings` are soft (logged, don't block). The LLM-judge
 * parity panel covers the editorial half (selection/voice/judgment) — this covers shape only.
 */
export interface ValidationResult {
  pass: boolean;
  failures: string[];
  warnings: string[];
  bytes: number;
}

// Canonical section spine per mode (heading text after the emoji is matched loosely on the keyword).
// "⏭ Next steps" added at the B3 canvas restructure (2026-07-07): daily-only, sits between
// 🧠 (now pure forward-looking) and 💼; older briefings simply omit it (present-in-order check —
// absent sections are always fine, so pre-B3 briefings still validate unchanged). NOTE the emoji
// is matched by startsWith, so both "⏭" and "⏭️" (VS16) headings pass.
const DAILY_SECTIONS = ["📅", "🧠", "⏭", "💼", "📚", "🌱", "📈"];
const WEEKEND_SECTIONS = ["🧭", "✅", "⏭", "💼", "📚", "🌱", "📈"];
// Gold-derived byte bands (daily gold 4073–4528; weekend gold 7045). Generous floors/ceilings.
// Floors lowered 2026-07-02: the first live week (holiday, thin inputs) produced legitimate
// 2.9–3.1KB dailies that hugged the old 2800B floor — a thin news day is a short briefing, not a
// failure. The floor's job is catching truncation/lazy output (typically <2KB or structurally
// broken, which the spine checks catch); it must not force padding on quiet days.
// Daily ceiling 6000 → 7000 at B3: the ⏭ Next steps section adds one id line per pending
// proposal (24 pending at cutover) — legitimate structure, not dumping. Ceiling stays a warning.
const BANDS: Record<BriefingMode, { min: number; max: number }> = {
  daily: { min: 2200, max: 7000 },
  // Weekend floor was 4000 (gold weekend = 7045B) until 2026-07-04: a holiday weekend produced
  // two honest ~3.5KB drafts and the floor rejected both — the floor's job is catching
  // truncation/derailment (<2KB), not arguing with CALIBRATION's "thin day = short briefing".
  weekend: { min: 2200, max: 9500 },
};
const FOOTER_MARKER = "Generated by the `briefing` skill";
const FULL_REPORT_LINK = "[Full library report](/api/reports/morning)";
const DAILY_REPORT_LINK = "[Daily library report](/api/reports/morning)";
const MEMO_LINK = "[Read the memo](/api/reports/memo)";

interface LibraryModuleSegment {
  heading: string;
  body: string;
}

function librarySectionBody(markdown: string): string | null {
  const lines = markdown.split("\n");
  const start = lines.findIndex((line) => /^##\s+.*(?:📚|library)/i.test(line));
  if (start === -1) return null;
  const endOffset = lines.slice(start + 1).findIndex((line) => /^##\s+/.test(line));
  const end = endOffset === -1 ? lines.length : start + 1 + endOffset;
  return lines.slice(start + 1, end).join("\n");
}

function libraryModuleSegments(section: string): LibraryModuleSegment[] {
  const matches = [...section.matchAll(/^###\s+(.+)$/gm)];
  return matches.map((match, index) => ({
    heading: match[1].trim(),
    body: section.slice((match.index || 0) + match[0].length, matches[index + 1]?.index ?? section.length).trim(),
  }));
}

function plainLeadText(markdown: string): string {
  return markdown
    .split("\n")
    .filter((line) => extractRecommendationEpisodeIds(line).length === 0)
    .filter((line) => !/^\s*\[[^\]]+]\([^)]*\)\s*$/.test(line))
    .join(" ")
    .replace(/!\[[^\]]*]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)]\([^)]*\)/g, "$1")
    .replace(/[*_`>#-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function wordCount(text: string): number {
  return text.match(/[A-Za-z0-9][A-Za-z0-9'-]*/g)?.length || 0;
}

function sentenceCount(text: string): number {
  return text.match(/[.!?](?:\s|$)/g)?.length || (text ? 1 : 0);
}

function sectionEmojisInOrder(markdown: string): string[] {
  const found: string[] = [];
  for (const line of markdown.split("\n")) {
    const m = line.match(/^##\s+(\S+)/);
    if (m) found.push(m[1]);
  }
  return found;
}

function topLevelSection(markdown: string, headingPattern: RegExp): { heading: string; body: string } | null {
  const lines = markdown.split("\n");
  const start = lines.findIndex((line) => {
    const heading = line.match(/^##\s+(.+)$/)?.[1] || "";
    return headingPattern.test(heading);
  });
  if (start === -1) return null;
  const endOffset = lines.slice(start + 1).findIndex((line) => /^##\s+/.test(line));
  const end = endOffset === -1 ? lines.length : start + 1 + endOffset;
  return { heading: lines[start].replace(/^##\s+/, ""), body: lines.slice(start + 1, end).join("\n") };
}

/** Of the canonical spine, the present ones must appear in canonical relative order (empty omitted ok). */
function orderViolation(present: string[], canonical: string[]): string | null {
  const filtered = present.filter((e) => canonical.some((c) => e.startsWith(c)));
  let lastIdx = -1;
  for (const emoji of filtered) {
    const idx = canonical.findIndex((c) => emoji.startsWith(c));
    if (idx < lastIdx) return `section "${emoji}" is out of canonical order`;
    lastIdx = idx;
  }
  return null;
}

export function validateBriefing(
  markdown: string,
  mode: BriefingMode,
  options: {
    allowedRecommendationEpisodeIds?: string[];
    libraryReportAvailable?: boolean;
    libraryHealthSummary?: string | null;
    libraryMemoExpected?: boolean;
    allowedDecisionTaskIds?: string[];
    decisionGroups?: Array<{ meeting: string; taskIds: string[]; taskTitles?: string[] }>;
  } = {},
): ValidationResult {
  const failures: string[] = [];
  const warnings: string[] = [];
  const bytes = Buffer.byteLength(markdown, "utf-8");
  const canonical = mode === "weekend" ? WEEKEND_SECTIONS : DAILY_SECTIONS;

  // H1
  const h1 = markdown.match(/^#\s+(.+)$/m)?.[1] ?? "";
  const wantH1 = mode === "weekend" ? /^Weekend Briefing —/ : /^Morning Briefing —/;
  if (!wantH1.test(h1.trim())) failures.push(`H1 missing/wrong: expected "${mode === "weekend" ? "Weekend" : "Morning"} Briefing — …", got "${h1.slice(0, 60)}"`);

  // Section spine: present canonical sections in order; no unknown ## sections that aren't canonical.
  const present = sectionEmojisInOrder(markdown);
  const ordErr = orderViolation(present, canonical);
  if (ordErr) failures.push(ordErr);
  const unknown = present.filter((e) => !canonical.some((c) => e.startsWith(c)));
  if (unknown.length) warnings.push(`non-canonical section heading(s): ${unknown.join(", ")}`);
  for (const must of mode === "daily" ? ["📅"] : ["🧭"]) {
    if (!present.some((e) => e.startsWith(must))) failures.push(`missing required lead section "${must}"`);
  }

  // The model owns meeting context and featured order. The harness reconciles canonical membership,
  // so IDs and their meeting association remain a hard contract without constraining the prose.
  if (options.allowedDecisionTaskIds !== undefined) {
    const expectedIds = [...new Set(options.allowedDecisionTaskIds)];
    const decisionSection = topLevelSection(markdown, /^⏭/);
    if (expectedIds.length > 0 && !decisionSection) failures.push(`missing "⏭ Decisions awaiting you" section`);
    if (expectedIds.length === 0 && decisionSection) failures.push(`Decisions section present with no pending proposal tasks`);
    if (decisionSection && !isDecisionsHeading(decisionSection.heading)) failures.push(`decision heading must be "⏭ Decisions awaiting you"`);

    const placedIds: string[] = [];
    let currentHeading = "";
    for (const line of markdown.split("\n")) {
      const heading = line.match(/^##\s+(.+)$/);
      if (heading) {
        currentHeading = heading[1];
        continue;
      }
      const ids = extractTaskIds(line);
      if (!ids.length) continue;
      if (!isDecisionsHeading(currentHeading)) {
        const leakedProposalIds = ids.filter((id) => expectedIds.includes(id));
        if (leakedProposalIds.length) failures.push(`proposal task id must be inside Decisions awaiting you: ${leakedProposalIds.join(", ")}`);
        continue;
      }
      placedIds.push(...ids);
      if (!isTaskIdOnlyLine(line) || ids.length !== 1) failures.push(`decision task-id line must contain only one task id: "${line.trim().slice(0, 100)}"`);
      for (const id of ids) if (!expectedIds.includes(id)) failures.push(`decision task id was not supplied: ${id}`);
    }
    const duplicates = placedIds.filter((id, index) => placedIds.indexOf(id) !== index);
    if (duplicates.length) failures.push(`decision task id placed more than once: ${[...new Set(duplicates)].join(", ")}`);
    const omitted = expectedIds.filter((id) => !placedIds.includes(id));
    if (omitted.length) failures.push(`supplied decision task id omitted: ${omitted.join(", ")}`);
    if (decisionSection && options.decisionGroups) {
      const lines = decisionSection.body.split("\n");
      for (const group of options.decisionGroups) {
        const citations = lines.flatMap((line, index) => isRedundantMeetingCitationLine(line, group.meeting) ? [index] : []);
        if (citations.length !== 1) {
          failures.push(`Decisions meeting must appear exactly once: ${group.meeting}`);
          continue;
        }
        let start = citations[0];
        while (start > 0 && !/^-\s+/.test(lines[start])) start -= 1;
        const next = lines.findIndex((line, index) => index > start && /^-\s+/.test(line));
        const end = next === -1 ? lines.length : next;
        const blockIds = extractTaskIds(lines.slice(start, end).join("\n"));
        for (const id of group.taskIds) {
          if (!blockIds.includes(id)) failures.push(`decision task id is not grouped with its meeting: ${id} → ${group.meeting}`);
        }
        const lead = lines[start].replace(/^\s*-\s*/, "").trim();
        if (lead.includes(`hilt:meeting/${group.meeting}`)) {
          failures.push(`Decisions meeting lead must not duplicate its citation as a pill: ${group.meeting}`);
        }
        if (/\b(?:one|two|three|four|five|six|seven|eight|nine|ten|\d+)\s+(?:pending|decisions?|asks?|proposals?)\b/i.test(lead)) {
          failures.push(`Decisions meeting context must not repeat a pending count: ${group.meeting}`);
        }
        if (group.taskTitles?.some((title) => decisionContextEchoesTaskTitle(lead, title))) {
          failures.push(`Decisions meeting context must not repeat TaskCard title prose: ${group.meeting}`);
        }
      }
    }
    for (const section of [topLevelSection(markdown, /^✅/), topLevelSection(markdown, /^💼/)]) {
      if (section && /pending verdicts|pending proposals|decisions awaiting you|meeting-actions[^\n]*(?:open entries|escalated items|pending actions)|\b\d+\s+(?:open entries|escalated items|pending actions)\b/i.test(section.body)) {
        failures.push(`${section.heading} duplicates the decisions queue`);
      }
    }
  }

  // No Sources section (citations live in sub-bullets).
  if (/^##\s+sources\b/im.test(markdown)) failures.push(`forbidden "Sources" section present`);

  // Library section contract. Calls without gather expectations keep the historical validator path;
  // native generation passes expectations and must use the structured three-module contract.
  const libraryBody = librarySectionBody(markdown);
  const libraryModules = libraryBody ? libraryModuleSegments(libraryBody) : [];
  const enforceLibraryModules = options.libraryReportAvailable !== undefined || libraryModules.length > 0;
  if (!enforceLibraryModules && !markdown.includes(FULL_REPORT_LINK)) failures.push(`missing required link: ${FULL_REPORT_LINK}`);
  if (enforceLibraryModules) {
    const normalizedHeadings = libraryModules.map((module) => module.heading.toLowerCase().replace(/[’']/g, "'"));
    const recommendationIndex = normalizedHeadings.indexOf("recommended for you");
    const memoIndex = normalizedHeadings.indexOf("editor's memo");
    const healthIndex = normalizedHeadings.indexOf("library health");
    if (recommendationIndex === -1) failures.push(`Library & knowledge missing "### Recommended for you"`);
    if (healthIndex === -1) failures.push(`Library & knowledge missing "### Library health"`);
    if (recommendationIndex >= 0 && healthIndex >= 0 && recommendationIndex > healthIndex) failures.push(`Library modules are out of order`);
    if (memoIndex >= 0 && (memoIndex < recommendationIndex || memoIndex > healthIndex)) failures.push(`Library modules are out of order`);
    if (mode === "daily" && memoIndex >= 0) failures.push(`weekday briefing must not include the weekly Editor's memo module`);
    if (mode === "weekend" && options.libraryMemoExpected === true && memoIndex === -1) failures.push(`weekend briefing omitted the supplied Editor's memo module`);
    if (options.libraryMemoExpected === false && memoIndex >= 0) failures.push(`briefing included an Editor's memo that was not supplied for this weekend`);
    if (memoIndex >= 0 && !libraryModules[memoIndex].body.includes(MEMO_LINK)) failures.push(`Editor's memo module missing ${MEMO_LINK}`);
    if (options.libraryReportAvailable === true && !libraryModules[healthIndex]?.body.includes(DAILY_REPORT_LINK)) failures.push(`Library health missing required link: ${DAILY_REPORT_LINK}`);
    if (options.libraryReportAvailable === false) {
      if (markdown.includes(DAILY_REPORT_LINK)) failures.push(`Library report link emitted even though the dated report is unavailable`);
      if (!/\b(?:unavailable|not available|missing)\b/i.test(libraryModules[healthIndex]?.body || "")) {
        failures.push(`Library health must state that today's report is unavailable`);
      }
    }
    if (options.libraryHealthSummary && !libraryModules[healthIndex]?.body.includes(options.libraryHealthSummary)) failures.push(`Library health did not preserve the supplied deterministic summary`);
  }
  const suppliedRecommendationIds = new Set(options.allowedRecommendationEpisodeIds || []);
  const placedRecommendationIds: string[] = [];
  let recommendationHeading = "";
  for (const line of markdown.split("\n")) {
    const heading = line.match(/^##\s+(.*)$/);
    if (heading) {
      recommendationHeading = heading[1];
      continue;
    }
    const ids = extractRecommendationEpisodeIds(line);
    if (!ids.length) continue;
    placedRecommendationIds.push(...ids);
    if (!(recommendationHeading.includes("📚") || /library/i.test(recommendationHeading))) {
      failures.push(`recommendation token must be inside Library & knowledge: ${ids.join(", ")}`);
    }
    if (!isRecommendationEpisodeOnlyLine(line)) {
      failures.push(`recommendation token line must contain only one supplied placement id: "${line.slice(0, 100)}"`);
    }
    for (const id of ids) {
      if (!suppliedRecommendationIds.has(id)) failures.push(`recommendation episode was not supplied: ${id}`);
    }
  }
  const duplicateRecommendationIds = placedRecommendationIds.filter((id, index) => placedRecommendationIds.indexOf(id) !== index);
  if (duplicateRecommendationIds.length) {
    failures.push(`recommendation episode placed more than once: ${[...new Set(duplicateRecommendationIds)].join(", ")}`);
  }
  const omittedRecommendationIds = [...suppliedRecommendationIds].filter((id) => !placedRecommendationIds.includes(id));
  if (omittedRecommendationIds.length) warnings.push(`supplied recommendation episode(s) omitted: ${omittedRecommendationIds.join(", ")}`);
  if (enforceLibraryModules) {
    const recommendationModule = libraryModules.find((module) => module.heading.toLowerCase() === "recommended for you");
    if (recommendationModule) {
      const lead = plainLeadText(recommendationModule.body);
      const count = placedRecommendationIds.length;
      const words = wordCount(lead);
      const sentences = sentenceCount(lead);
      if (count >= 2 && (words < 40 || words > 90 || sentences < 2 || sentences > 3)) {
        failures.push(`recommendation lead must be 2-3 sentences and 40-90 words for ${count} picks (got ${sentences} sentences, ${words} words)`);
      } else if (count === 1 && (words < 20 || words > 45 || sentences < 1 || sentences > 2)) {
        failures.push(`recommendation lead must be 1-2 sentences and 20-45 words for one pick (got ${sentences} sentences, ${words} words)`);
      } else if (count === 0 && lead !== "Nothing new was selected for this briefing.") {
        failures.push(`zero-recommendation Library lead must use the quiet no-selection sentence exactly`);
      }
    }
  }
  // Memo-link rule: FEATURING the editor's memo (a bold span or heading naming it) requires the
  // memo link ON THAT LINE. Merely REFERENCING it — an italic citation sub-bullet
  // ("*…; Editor's memo, 6/28.*") or passing prose — does not. The original any-mention/any-where
  // regex caused 2 of the first 3 live mornings to fail validation on citation-only mentions
  // (2026-06-30/07-01 .invalid-drafts), burning 50–80 min of retries each; and a document-level
  // link check would let a second unlinked featured line ride a linked one (Codex review).
  const featuredLine = /(\*\*[^*\n]*editor'?s\s+memo[^*\n]*\*\*)|(^#{1,6}\s+.*editor'?s\s+memo)/i;
  // The day-thesis lede (everything before the first section heading) is exempt: it's a summary
  // sentence where inline links are against house style — mentioning the memo there is fine.
  // This exact rule tripped three honest drafts (06-10, 07-06 ×2) purely on bold ledes.
  const firstHeading = markdown.search(/^##\s/m);
  const body = firstHeading === -1 ? markdown : markdown.slice(firstHeading);
  // The link may sit on the featured line OR the immediately-following non-empty line — the
  // LINKS style rule mandates standalone link lines, and 07-06 proved a model can't satisfy
  // both "inline on that line" and "never inline" at once.
  if (!enforceLibraryModules) {
    const bodyLines = body.split("\n");
    for (let i = 0; i < bodyLines.length; i++) {
      const line = bodyLines[i];
      if (!featuredLine.test(line) || line.includes(MEMO_LINK)) continue;
      let j = i + 1;
      while (j < bodyLines.length && bodyLines[j].trim() === "") j++;
      if (j < bodyLines.length && bodyLines[j].includes(MEMO_LINK)) continue;
      failures.push(`editor's memo is featured (bold/heading) without ${MEMO_LINK} on that line or the next: "${line.slice(0, 80)}"`);
    }
  }

  // Citation-only sub-bullets (B5 pill citations — SOFT, never a failure): sub-bullets should
  // be EVIDENCE (a fact, a quote, a delta); a detail line that is ONLY an italic `*source, date*`
  // citation span duplicates what an inline `hilt:` pill citation already carries. The ⏭ Next
  // steps section is exempt — its meeting-citation first sub-bullet is the load-bearing join key
  // of the id contract (canvas.ts), not reading material.
  let currentHeading = "";
  for (const line of markdown.split("\n")) {
    const heading = line.match(/^##\s+(.*)/);
    if (heading) { currentHeading = heading[1]; continue; }
    if (currentHeading.includes("⏭")) continue;
    const sub = line.match(/^\s{2,}-\s+(.*)$/);
    if (!sub) continue;
    // `*loop:<id>, <item-id>*` spans are the LOAD-BEARING ask-binding join key (SKILL: "exact
    // form is load-bearing") — warning on them coaches the generator to break its own contract
    // (B5 adversarial finding; there is no hilt: kind for loop items).
    if (/^\*loop:/.test(sub[1].trim())) continue;
    if (/^\*[^*]+\*[\s.,;:]*$/.test(sub[1].trim())) {
      warnings.push(`citation-only sub-bullet (sub-bullets are evidence; cite objects inline as [name](hilt:kind/id) pills): "${line.trim().slice(0, 80)}"`);
    }
  }

  // Footer.
  if (!markdown.includes(FOOTER_MARKER)) failures.push(`missing footer ("${FOOTER_MARKER}…")`);

  // Weekend frontmatter.
  if (mode === "weekend") {
    const fm = markdown.match(/^---\n([\s\S]*?)\n---/);
    if (!fm) failures.push(`weekend briefing missing YAML frontmatter`);
    else {
      const body = fm[1];
      for (const key of ["briefing_kind", "date_range", "created_at", "updated_at", "title"]) {
        if (!new RegExp(`(^|\\n)\\s*${key}\\b`).test(body)) failures.push(`weekend frontmatter missing "${key}"`);
      }
      if (!/briefing_kind:\s*weekend/.test(body)) failures.push(`weekend frontmatter: briefing_kind must be "weekend"`);
    }
  } else if (/^---\n/.test(markdown)) {
    warnings.push(`daily briefing has frontmatter (gold dailies have none)`);
  }

  // Length band (soft-ish: floor failure = too thin to be useful; ceiling warning unless way over).
  const band = BANDS[mode];
  if (bytes < band.min) failures.push(`too short: ${bytes}B < floor ${band.min}B (gold band)`);
  else if (bytes > band.max) warnings.push(`long: ${bytes}B > ${band.max}B (gold daily ~4–4.5KB)`);

  return { pass: failures.length === 0, failures, warnings, bytes };
}
