import { test } from "node:test";
import assert from "node:assert/strict";
import { validateBriefing } from "./validator";

const FOOTER = "\n\n---\n*Generated by the `briefing` skill. To change this, edit the skill.*\n";
const REPORT = "[Full library report](/api/reports/morning)";

// A complete, structurally-valid daily, padded into the gold byte band (~4KB).
function validDaily(): string {
  const filler = "  - Supporting detail with a real fact and a citation. *git: hilt, 6/26*\n".repeat(40);
  return `# Morning Briefing — Friday, June 26, 2026

## 📅 Today
- **9:00am** standup; protect the **9–11am** runway before the GTM review.
${filler}
## 🧠 Don't drop this
- **Seb deep dive** due **6/30**.
  - Floating commitment from the 1:1. *meeting, 6/24*

## 💼 Work & product
- EverPro reforecast is sales-coupled.
  - Threads to last week's flagged risk. *git: everpro, 6/25*

## 📚 Library & knowledge
- One proposal awaiting your verdict.
  - ${REPORT}

## 📈 System
- All green.
${FOOTER}`;
}

test("a complete valid daily passes", () => {
  const r = validateBriefing(validDaily(), "daily");
  assert.equal(r.pass, true, `unexpected failures: ${r.failures.join(" | ")}`);
});

test("fresh editor's-memo headline without the memo link is a hard failure", () => {
  const md = validDaily().replace(
    "- One proposal awaiting your verdict.",
    "- **Editor's memo:** AI magnifies what you bring.\n- One proposal awaiting your verdict.",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, false);
  assert.ok(r.failures.some((f) => f.includes("Read the memo")), r.failures.join(" | "));
});

test("editor's-memo headline WITH the memo link passes that rule", () => {
  const md = validDaily().replace(
    "- One proposal awaiting your verdict.",
    "- **Editor's memo:** AI magnifies what you bring. [Read the memo](/api/reports/memo)\n- One proposal awaiting your verdict.",
  );
  const r = validateBriefing(md, "daily");
  assert.ok(!r.failures.some((f) => f.includes("Read the memo")), r.failures.join(" | "));
});

// Featuring vs. referencing (2026-07-02 fix): the 06-30 live run failed validation on a mere
// CITATION mention of the memo — the rule must only fire on featured (bold/heading) usage.
test("a citation-only memo mention (italic sub-bullet) does NOT require the memo link", () => {
  const md = validDaily().replace(
    "  - Floating commitment from the 1:1. *meeting, 6/24*",
    "  - *lists/now/2026-06-29.md; Editor's memo, 6/28.*",
  );
  const r = validateBriefing(md, "daily");
  assert.ok(!r.failures.some((f) => f.includes("Read the memo")), r.failures.join(" | "));
});

test("passing-prose memo mention does NOT require the memo link", () => {
  const md = validDaily().replace(
    "- EverPro reforecast is sales-coupled.",
    "- The framing is locked from the editor's memo and yesterday's briefing.",
  );
  const r = validateBriefing(md, "daily");
  assert.ok(!r.failures.some((f) => f.includes("Read the memo")), r.failures.join(" | "));
});

test("a bold stale-memo reference still requires the link (featured usage)", () => {
  const md = validDaily().replace(
    "- One proposal awaiting your verdict.",
    "- **Editor's memo from 6/28 is still the through-line** — verification gap as Seb pitch.\n- One proposal awaiting your verdict.",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, false);
  assert.ok(r.failures.some((f) => f.includes("Read the memo")), r.failures.join(" | "));
});

test("a heading naming the memo requires the link", () => {
  const md = validDaily() + "\n### Editor's memo highlights\n- thing\n";
  const r = validateBriefing(md, "daily");
  assert.ok(r.failures.some((f) => f.includes("Read the memo")), r.failures.join(" | "));
});

test("per-line rule: a second unlinked featured memo line fails even when another line has the link", () => {
  const md = validDaily().replace(
    "- One proposal awaiting your verdict.",
    "- **Editor's memo:** thesis here. [Read the memo](/api/reports/memo)\n- **Editor's memo follow-up is unlinked** — sneaky.\n- One proposal awaiting your verdict.",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, false);
  assert.ok(r.failures.some((f) => f.includes("sneaky") || f.includes("follow-up")), r.failures.join(" | "));
});

test("missing Full library report link fails", () => {
  const r = validateBriefing(validDaily().replace(REPORT, ""), "daily");
  assert.ok(r.failures.some((f) => f.includes("Full library report")));
});

test("a Sources section is forbidden", () => {
  const r = validateBriefing(validDaily() + "\n## Sources\n- [1] x\n", "daily");
  assert.ok(r.failures.some((f) => f.includes("Sources")));
});

// ── B3 canvas: the ⏭ Next steps section ────────────────────────────────────────────────────

test("a daily with ⏭ Next steps between 🧠 and 💼 passes (B3 spine)", () => {
  const md = validDaily().replace(
    "## 💼 Work & product",
    "## ⏭ Next steps\n- **OC planning (6/30)** — Phase 2 verbally approved; campaign outline is the deliverable\n  - *meetings/2026-06-30/OC planning-2026-06-30.md, 2026-06-30*\n  - `t-20260707-001`\n  - `t-20260707-002`\n\n## 💼 Work & product",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, true, `unexpected failures: ${r.failures.join(" | ")}`);
  assert.ok(!r.warnings.some((w) => w.includes("⏭")), `⏭ must be canonical, not unknown: ${r.warnings.join(" | ")}`);
});

test("a VS16 ⏭️ Next steps heading is also canonical", () => {
  const md = validDaily().replace(
    "## 💼 Work & product",
    "## ⏭️ Next steps\n- **OC planning (6/30)** — outline due\n  - `t-20260707-001`\n\n## 💼 Work & product",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, true, `unexpected failures: ${r.failures.join(" | ")}`);
  assert.ok(!r.warnings.some((w) => w.includes("⏭")), r.warnings.join(" | "));
});

test("⏭ Next steps AFTER 💼 is out of canonical order", () => {
  const md = validDaily().replace(
    "## 📚 Library & knowledge",
    "## ⏭ Next steps\n- entry\n  - `t-20260707-001`\n\n## 📚 Library & knowledge",
  );
  const r = validateBriefing(md, "daily");
  assert.ok(r.failures.some((f) => f.includes("order")), r.failures.join(" | "));
});

test("a pre-B3 daily (no ⏭ section) still validates unchanged", () => {
  // validDaily() has no ⏭ section — the canonical spine only constrains PRESENT sections.
  const r = validateBriefing(validDaily(), "daily");
  assert.equal(r.pass, true, `unexpected failures: ${r.failures.join(" | ")}`);
});

// ── B5 pill citations: citation-only sub-bullets are a SOFT warning, never a failure ────────

test("a citation-only sub-bullet warns but never fails", () => {
  const md = validDaily().replace(
    "  - Threads to last week's flagged risk. *git: everpro, 6/25*",
    "  - Threads to last week's flagged risk.\n  - *meetings/2026-06-25/EverPro sync-2026-06-25.md, 2026-06-25*",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, true, `must stay soft — unexpected failures: ${r.failures.join(" | ")}`);
  assert.ok(r.warnings.some((w) => w.includes("citation-only")), r.warnings.join(" | "));
});

test("evidence sub-bullets with trailing citations do NOT warn", () => {
  // validDaily()'s sub-bullets all carry real prose before their citations.
  const r = validateBriefing(validDaily(), "daily");
  assert.ok(!r.warnings.some((w) => w.includes("citation-only")), r.warnings.join(" | "));
});

test("the ⏭ meeting-citation sub-bullet is exempt (load-bearing join key, not reading material)", () => {
  const md = validDaily().replace(
    "## 💼 Work & product",
    "## ⏭ Next steps\n- **OC planning (6/30)** — Phase 2 verbally approved\n  - *meetings/2026-06-30/OC planning-2026-06-30.md, 2026-06-30*\n  - `t-20260707-001`\n\n## 💼 Work & product",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, true, `unexpected failures: ${r.failures.join(" | ")}`);
  assert.ok(!r.warnings.some((w) => w.includes("citation-only")), r.warnings.join(" | "));
});

test("out-of-order sections fail", () => {
  const md = validDaily().replace("## 📈 System", "## 📅 System"); // a second 📅 after 📚 → order break
  const r = validateBriefing(md, "daily");
  assert.ok(r.failures.some((f) => f.includes("order")), r.failures.join(" | "));
});

test("too-thin daily fails the length floor", () => {
  const tiny = `# Morning Briefing — Friday, June 26, 2026\n\n## 📅 Today\n- thin ${REPORT}\n${FOOTER}`;
  const r = validateBriefing(tiny, "daily");
  assert.ok(r.failures.some((f) => f.includes("too short")));
});

test("weekend requires frontmatter with the required keys", () => {
  const noFm = `# Weekend Briefing — Jun 20-21, 2026\n\n## 🧭 Direction of travel\n- x\n  - ${REPORT}\n${FOOTER}`;
  const r = validateBriefing(noFm, "weekend");
  assert.ok(r.failures.some((f) => f.includes("frontmatter")));
});

test("a valid weekend (frontmatter + sections + links + footer) passes", () => {
  const body = "  - Weekly direction detail with a fact. *git: hilt, 6/20*\n".repeat(70);
  const md = `---
briefing_kind: weekend
date_range:
  start: 2026-06-20
  end: 2026-06-21
created_at: 2026-06-20T06:00:00-04:00
updated_at: 2026-06-20T06:00:00-04:00
title: Weekend Briefing — Jun 20-21, 2026
---

# Weekend Briefing — Jun 20-21, 2026

## 🧭 Direction of travel
- The week's through-line.
${body}
## 📚 Library & knowledge
- Thematic substance.
  - ${REPORT}
${FOOTER}`;
  const r = validateBriefing(md, "weekend");
  assert.equal(r.pass, true, `unexpected failures: ${r.failures.join(" | ")}`);
});
