import type { BriefingMode } from "./target-file";

/**
 * Structural gate for a generated briefing — the deterministic half of "verified parity". Encodes the
 * contract derived from SKILL.md + the real Hermes gold briefings (and the two findings from the
 * parity-verification workflow: the gold daily band is ~4.0–4.5KB, NOT the 1.6–2.5KB first guessed;
 * and a fresh editor's-memo headline MUST carry the [Read the memo] link — that was the one miss).
 *
 * `failures` are hard (block publish); `warnings` are soft (logged, don't block). The LLM-judge
 * parity panel covers the editorial half (selection/voice/judgment) — this covers shape only.
 */
export interface ValidationResult {
  pass: boolean;
  failures: string[];
  warnings: string[];
  bytes: number;
}

// Canonical section spine per mode (heading text after the emoji is matched loosely on the keyword).
const DAILY_SECTIONS = ["📅", "🧠", "💼", "📚", "🌱", "📈"];
const WEEKEND_SECTIONS = ["🧭", "✅", "💼", "📚", "🌱", "📈"];
// Gold-derived byte bands (daily gold 4073–4528; weekend gold 7045). Generous floors/ceilings.
const BANDS: Record<BriefingMode, { min: number; max: number }> = {
  daily: { min: 2800, max: 6000 },
  weekend: { min: 4500, max: 9500 },
};
const FOOTER_MARKER = "Generated by the `briefing` skill";
const FULL_REPORT_LINK = "[Full library report](/api/reports/morning)";
const MEMO_LINK = "[Read the memo](/api/reports/memo)";

function sectionEmojisInOrder(markdown: string): string[] {
  const found: string[] = [];
  for (const line of markdown.split("\n")) {
    const m = line.match(/^##\s+(\S+)/);
    if (m) found.push(m[1]);
  }
  return found;
}

/** Of the canonical spine, the present ones must appear in canonical relative order (empty omitted ok). */
function orderViolation(present: string[], canonical: string[]): string | null {
  const filtered = present.filter((e) => canonical.some((c) => e.startsWith(c)));
  let lastIdx = -1;
  for (const emoji of filtered) {
    const idx = canonical.findIndex((c) => emoji.startsWith(c));
    if (idx < lastIdx) return `section "${emoji}" is out of canonical order`;
    lastIdx = idx;
  }
  return null;
}

export function validateBriefing(markdown: string, mode: BriefingMode): ValidationResult {
  const failures: string[] = [];
  const warnings: string[] = [];
  const bytes = Buffer.byteLength(markdown, "utf-8");
  const canonical = mode === "weekend" ? WEEKEND_SECTIONS : DAILY_SECTIONS;

  // H1
  const h1 = markdown.match(/^#\s+(.+)$/m)?.[1] ?? "";
  const wantH1 = mode === "weekend" ? /^Weekend Briefing —/ : /^Morning Briefing —/;
  if (!wantH1.test(h1.trim())) failures.push(`H1 missing/wrong: expected "${mode === "weekend" ? "Weekend" : "Morning"} Briefing — …", got "${h1.slice(0, 60)}"`);

  // Section spine: present canonical sections in order; no unknown ## sections that aren't canonical.
  const present = sectionEmojisInOrder(markdown);
  const ordErr = orderViolation(present, canonical);
  if (ordErr) failures.push(ordErr);
  const unknown = present.filter((e) => !canonical.some((c) => e.startsWith(c)));
  if (unknown.length) warnings.push(`non-canonical section heading(s): ${unknown.join(", ")}`);
  for (const must of mode === "daily" ? ["📅"] : ["🧭"]) {
    if (!present.some((e) => e.startsWith(must))) failures.push(`missing required lead section "${must}"`);
  }

  // No Sources section (citations live in sub-bullets).
  if (/^##\s+sources\b/im.test(markdown)) failures.push(`forbidden "Sources" section present`);

  // Library section contract.
  if (!markdown.includes(FULL_REPORT_LINK)) failures.push(`missing required link: ${FULL_REPORT_LINK}`);
  // Fail-closed memo-link rule: a fresh editor's-memo headline REQUIRES the memo link.
  if (/editor'?s\s+memo/i.test(markdown) && !markdown.includes(MEMO_LINK)) {
    failures.push(`fresh editor's-memo headline present but missing ${MEMO_LINK}`);
  }

  // Footer.
  if (!markdown.includes(FOOTER_MARKER)) failures.push(`missing footer ("${FOOTER_MARKER}…")`);

  // Weekend frontmatter.
  if (mode === "weekend") {
    const fm = markdown.match(/^---\n([\s\S]*?)\n---/);
    if (!fm) failures.push(`weekend briefing missing YAML frontmatter`);
    else {
      const body = fm[1];
      for (const key of ["briefing_kind", "date_range", "created_at", "updated_at", "title"]) {
        if (!new RegExp(`(^|\\n)\\s*${key}\\b`).test(body)) failures.push(`weekend frontmatter missing "${key}"`);
      }
      if (!/briefing_kind:\s*weekend/.test(body)) failures.push(`weekend frontmatter: briefing_kind must be "weekend"`);
    }
  } else if (/^---\n/.test(markdown)) {
    warnings.push(`daily briefing has frontmatter (gold dailies have none)`);
  }

  // Length band (soft-ish: floor failure = too thin to be useful; ceiling warning unless way over).
  const band = BANDS[mode];
  if (bytes < band.min) failures.push(`too short: ${bytes}B < floor ${band.min}B (gold band)`);
  else if (bytes > band.max) warnings.push(`long: ${bytes}B > ${band.max}B (gold daily ~4–4.5KB)`);

  return { pass: failures.length === 0, failures, warnings, bytes };
}
