import { test } from "node:test";
import assert from "node:assert/strict";
import { validateBriefing } from "./validator";

const FOOTER = "\n\n---\n*Generated by the `briefing` skill. To change this, edit the skill.*\n";
const REPORT = "[Full library report](/api/reports/morning)";
const DAILY_REPORT = "[Daily library report](/api/reports/morning)";
const EPISODES = [
  "rec-20260710052000-01-ab12cd34",
  "rec-20260710052000-02-ef56ab78",
  "rec-20260710052000-03-cd90ef12",
];
const HEALTH = "Library processing is healthy; two steering proposals await review, and judge agreement is 74%.";

// A complete, structurally-valid daily, padded into the gold byte band (~4KB).
function validDaily(): string {
  const filler = "  - Supporting detail with a real fact and a citation. *git: hilt, 6/26*\n".repeat(40);
  return `# Morning Briefing — Friday, June 26, 2026

## 📅 Today
- **9:00am** standup; protect the **9–11am** runway before the GTM review.
${filler}
## 🧠 Don't drop this
- **Seb deep dive** due **6/30**.
  - Floating commitment from the 1:1. *meeting, 6/24*

## 💼 Work & product
- EverPro reforecast is sales-coupled.
  - Threads to last week's flagged risk. *git: everpro, 6/25*

## 📚 Library & knowledge
- One proposal awaiting your verdict.
  - ${REPORT}

## 📈 System
- All green.
${FOOTER}`;
}

function withStructuredLibrary(markdown: string, body: string): string {
  return markdown.replace(
    `- One proposal awaiting your verdict.\n  - ${REPORT}`,
    body,
  );
}

function validWeekend(): string {
  const body = "  - Weekly direction detail with a fact. *git: hilt, 6/20*\n".repeat(70);
  return `---
briefing_kind: weekend
date_range:
  start: 2026-06-20
  end: 2026-06-21
created_at: 2026-06-20T06:00:00-04:00
updated_at: 2026-06-20T06:00:00-04:00
title: Weekend Briefing — Jun 20-21, 2026
---

# Weekend Briefing — Jun 20-21, 2026

## 🧭 Direction of travel
- The week's through-line.
${body}
## 📚 Library & knowledge
- Thematic substance.
  - ${REPORT}
${FOOTER}`;
}

test("a complete valid daily passes", () => {
  const r = validateBriefing(validDaily(), "daily");
  assert.equal(r.pass, true, `unexpected failures: ${r.failures.join(" | ")}`);
});

test("fresh editor's-memo headline without the memo link is a hard failure", () => {
  const md = validDaily().replace(
    "- One proposal awaiting your verdict.",
    "- **Editor's memo:** AI magnifies what you bring.\n- One proposal awaiting your verdict.",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, false);
  assert.ok(r.failures.some((f) => f.includes("Read the memo")), r.failures.join(" | "));
});

test("editor's-memo headline WITH the memo link passes that rule", () => {
  const md = validDaily().replace(
    "- One proposal awaiting your verdict.",
    "- **Editor's memo:** AI magnifies what you bring. [Read the memo](/api/reports/memo)\n- One proposal awaiting your verdict.",
  );
  const r = validateBriefing(md, "daily");
  assert.ok(!r.failures.some((f) => f.includes("Read the memo")), r.failures.join(" | "));
});

// Featuring vs. referencing (2026-07-02 fix): the 06-30 live run failed validation on a mere
// CITATION mention of the memo — the rule must only fire on featured (bold/heading) usage.
test("a citation-only memo mention (italic sub-bullet) does NOT require the memo link", () => {
  const md = validDaily().replace(
    "  - Floating commitment from the 1:1. *meeting, 6/24*",
    "  - *lists/now/2026-06-29.md; Editor's memo, 6/28.*",
  );
  const r = validateBriefing(md, "daily");
  assert.ok(!r.failures.some((f) => f.includes("Read the memo")), r.failures.join(" | "));
});

test("passing-prose memo mention does NOT require the memo link", () => {
  const md = validDaily().replace(
    "- EverPro reforecast is sales-coupled.",
    "- The framing is locked from the editor's memo and yesterday's briefing.",
  );
  const r = validateBriefing(md, "daily");
  assert.ok(!r.failures.some((f) => f.includes("Read the memo")), r.failures.join(" | "));
});

test("a bold stale-memo reference still requires the link (featured usage)", () => {
  const md = validDaily().replace(
    "- One proposal awaiting your verdict.",
    "- **Editor's memo from 6/28 is still the through-line** — verification gap as Seb pitch.\n- One proposal awaiting your verdict.",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, false);
  assert.ok(r.failures.some((f) => f.includes("Read the memo")), r.failures.join(" | "));
});

test("a heading naming the memo requires the link", () => {
  const md = validDaily() + "\n### Editor's memo highlights\n- thing\n";
  const r = validateBriefing(md, "daily");
  assert.ok(r.failures.some((f) => f.includes("Read the memo")), r.failures.join(" | "));
});

test("per-line rule: a second unlinked featured memo line fails even when another line has the link", () => {
  const md = validDaily().replace(
    "- One proposal awaiting your verdict.",
    "- **Editor's memo:** thesis here. [Read the memo](/api/reports/memo)\n- **Editor's memo follow-up is unlinked** — sneaky.\n- One proposal awaiting your verdict.",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, false);
  assert.ok(r.failures.some((f) => f.includes("sneaky") || f.includes("follow-up")), r.failures.join(" | "));
});

test("missing Full library report link fails", () => {
  const r = validateBriefing(validDaily().replace(REPORT, ""), "daily");
  assert.ok(r.failures.some((f) => f.includes("Full library report")));
});

test("recommendation placement accepts supplied IDs only inside Library on token-only lines", () => {
  const episode = "rec-20260710052000-01-ab12cd34";
  const md = validDaily().replace(
    "- One proposal awaiting your verdict.",
    `- \`rec:${episode}\`\n- One proposal awaiting your verdict.`,
  );
  const valid = validateBriefing(md, "daily", { allowedRecommendationEpisodeIds: [episode] });
  assert.ok(!valid.failures.some((failure) => /recommendation/.test(failure)), valid.failures.join(" | "));

  const invented = validateBriefing(md, "daily", { allowedRecommendationEpisodeIds: [] });
  assert.ok(invented.failures.some((failure) => failure.includes("not supplied")));

  const annotated = validateBriefing(md.replace(`- \`rec:${episode}\``, `- Read this now \`rec:${episode}\``), "daily", { allowedRecommendationEpisodeIds: [episode] });
  assert.ok(annotated.failures.some((failure) => failure.includes("token line")));

  const outside = validateBriefing(validDaily().replace(
    "- EverPro reforecast is sales-coupled.",
    `- \`rec:${episode}\`\n- EverPro reforecast is sales-coupled.`,
  ), "daily", { allowedRecommendationEpisodeIds: [episode] });
  assert.ok(outside.failures.some((failure) => failure.includes("inside Library")));
});

test("fewer than three supplied recommendations are valid and omissions are soft", () => {
  const first = "rec-20260710052000-01-ab12cd34";
  const second = "rec-20260710052000-02-ef56ab78";
  const md = validDaily().replace("- One proposal awaiting your verdict.", `- \`rec:${first}\`\n- One proposal awaiting your verdict.`);
  const result = validateBriefing(md, "daily", { allowedRecommendationEpisodeIds: [first, second] });
  assert.ok(!result.failures.some((failure) => /recommendation/.test(failure)));
  assert.ok(result.warnings.some((warning) => warning.includes(second)));
});

test("structured daily Library modules accept a 2-sentence editorial lead and exact health", () => {
  const lead = "The attention system is moving from static ranking toward contextual judgment, and today's picks expose the product decisions that make that shift credible. Together they connect source quality, interface clarity, and validation discipline so the next implementation review can focus on consequences rather than scores.";
  const md = withStructuredLibrary(validDaily(), `### Recommended for you
${lead}

${EPISODES.map((id) => `- \`rec:${id}\``).join("\n")}

### Library health
${HEALTH}

${DAILY_REPORT}`);
  const result = validateBriefing(md, "daily", {
    allowedRecommendationEpisodeIds: EPISODES,
    libraryReportAvailable: true,
    libraryHealthSummary: HEALTH,
    libraryMemoExpected: false,
  });
  assert.equal(result.pass, true, result.failures.join(" | "));
});

test("structured daily supports one or zero recommendations without padding", () => {
  const one = withStructuredLibrary(validDaily(), `### Recommended for you
A new implementation decision makes this source immediately useful: its validation pattern offers a concrete way to inspect the recommendation experience before today's review.

- \`rec:${EPISODES[0]}\`

### Library health
${HEALTH}

${DAILY_REPORT}`);
  const oneResult = validateBriefing(one, "daily", {
    allowedRecommendationEpisodeIds: [EPISODES[0]],
    libraryReportAvailable: true,
    libraryHealthSummary: HEALTH,
    libraryMemoExpected: false,
  });
  assert.equal(oneResult.pass, true, oneResult.failures.join(" | "));

  const zero = withStructuredLibrary(validDaily(), `### Recommended for you
Nothing new was selected for this briefing.

### Library health
${HEALTH}

${DAILY_REPORT}`);
  const zeroResult = validateBriefing(zero, "daily", {
    allowedRecommendationEpisodeIds: [],
    libraryReportAvailable: true,
    libraryHealthSummary: HEALTH,
    libraryMemoExpected: false,
  });
  assert.equal(zeroResult.pass, true, zeroResult.failures.join(" | "));
});

test("structured Library rejects duplicate copy roles, invalid ordering, and an unavailable report link", () => {
  const tooShort = withStructuredLibrary(validDaily(), `### Recommended for you
Read these now.

${EPISODES.map((id) => `- \`rec:${id}\``).join("\n")}

### Library health
${HEALTH}

${DAILY_REPORT}`);
  const shortResult = validateBriefing(tooShort, "daily", {
    allowedRecommendationEpisodeIds: EPISODES,
    libraryReportAvailable: true,
    libraryHealthSummary: HEALTH,
  });
  assert.ok(shortResult.failures.some((failure) => failure.includes("40-90 words")));

  const unavailable = withStructuredLibrary(validDaily(), `### Recommended for you
Nothing new was selected for this briefing.

### Library health
${HEALTH}

${DAILY_REPORT}`);
  const unavailableResult = validateBriefing(unavailable, "daily", {
    allowedRecommendationEpisodeIds: [],
    libraryReportAvailable: false,
    libraryHealthSummary: HEALTH,
  });
  assert.ok(unavailableResult.failures.some((failure) => failure.includes("unavailable")));
});

test("a Sources section is forbidden", () => {
  const r = validateBriefing(validDaily() + "\n## Sources\n- [1] x\n", "daily");
  assert.ok(r.failures.some((f) => f.includes("Sources")));
});

// ── B3 canvas: the ⏭ Next steps section ────────────────────────────────────────────────────

test("a daily with ⏭ Next steps between 🧠 and 💼 passes (B3 spine)", () => {
  const md = validDaily().replace(
    "## 💼 Work & product",
    "## ⏭ Next steps\n- **OC planning (6/30)** — Phase 2 verbally approved; campaign outline is the deliverable\n  - *meetings/2026-06-30/OC planning-2026-06-30.md, 2026-06-30*\n  - `t-20260707-001`\n  - `t-20260707-002`\n\n## 💼 Work & product",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, true, `unexpected failures: ${r.failures.join(" | ")}`);
  assert.ok(!r.warnings.some((w) => w.includes("⏭")), `⏭ must be canonical, not unknown: ${r.warnings.join(" | ")}`);
});

test("a VS16 ⏭️ Next steps heading is also canonical", () => {
  const md = validDaily().replace(
    "## 💼 Work & product",
    "## ⏭️ Next steps\n- **OC planning (6/30)** — outline due\n  - `t-20260707-001`\n\n## 💼 Work & product",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, true, `unexpected failures: ${r.failures.join(" | ")}`);
  assert.ok(!r.warnings.some((w) => w.includes("⏭")), r.warnings.join(" | "));
});

test("⏭ Next steps AFTER 💼 is out of canonical order", () => {
  const md = validDaily().replace(
    "## 📚 Library & knowledge",
    "## ⏭ Next steps\n- entry\n  - `t-20260707-001`\n\n## 📚 Library & knowledge",
  );
  const r = validateBriefing(md, "daily");
  assert.ok(r.failures.some((f) => f.includes("order")), r.failures.join(" | "));
});

test("a pre-B3 daily (no ⏭ section) still validates unchanged", () => {
  // validDaily() has no ⏭ section — the canonical spine only constrains PRESENT sections.
  const r = validateBriefing(validDaily(), "daily");
  assert.equal(r.pass, true, `unexpected failures: ${r.failures.join(" | ")}`);
});

test("editorial Decisions requires exact supplied ids, meeting grouping, placement, and heading", () => {
  const md = validDaily().replace(
    "## 💼 Work & product",
    "## ⏭ Decisions awaiting you\n\n- Planning aligned the implementation path, but scope and ownership still block the next handoff.\n  - *meetings/2026-07-10/Planning.md, 2026-07-10*\n  - `t-20260710-001`\n  - `t-20260710-002`\n\n## 💼 Work & product",
  );
  const valid = validateBriefing(md, "daily", {
    allowedDecisionTaskIds: ["t-20260710-001", "t-20260710-002"],
    decisionGroups: [{ meeting: "meetings/2026-07-10/Planning.md", taskIds: ["t-20260710-001", "t-20260710-002"], taskTitles: ["Choose launch scope", "Name the implementation owner"] }],
  });
  assert.equal(valid.pass, true, valid.failures.join(" | "));

  const missing = validateBriefing(md.replace("  - `t-20260710-002`\n", ""), "daily", {
    allowedDecisionTaskIds: ["t-20260710-001", "t-20260710-002"],
    decisionGroups: [{ meeting: "meetings/2026-07-10/Planning.md", taskIds: ["t-20260710-001", "t-20260710-002"] }],
  });
  assert.ok(missing.failures.some((failure) => failure.includes("omitted")), missing.failures.join(" | "));

  const leaked = validateBriefing(md.replace("- EverPro reforecast is sales-coupled.", "- EverPro reforecast is sales-coupled. `t-20260710-001`"), "daily", {
    allowedDecisionTaskIds: ["t-20260710-001", "t-20260710-002"],
    decisionGroups: [{ meeting: "meetings/2026-07-10/Planning.md", taskIds: ["t-20260710-001", "t-20260710-002"] }],
  });
  assert.ok(leaked.failures.some((failure) => failure.includes("inside Decisions")), leaked.failures.join(" | "));

  const wrongGroup = validateBriefing(md.replace(
    "  - `t-20260710-002`",
    "- Another meeting introduced a separate question.\n  - *meetings/2026-07-10/Other.md, 2026-07-10*\n  - `t-20260710-002`",
  ), "daily", {
    allowedDecisionTaskIds: ["t-20260710-001", "t-20260710-002"],
    decisionGroups: [{ meeting: "meetings/2026-07-10/Planning.md", taskIds: ["t-20260710-001", "t-20260710-002"] }],
  });
  assert.ok(wrongGroup.failures.some((failure) => failure.includes("not grouped")), wrongGroup.failures.join(" | "));

  const counted = validateBriefing(md.replace("Planning aligned the implementation path, but scope and ownership still block the next handoff.", "Planning aligned the implementation path; one pending decision remains."), "daily", {
    allowedDecisionTaskIds: ["t-20260710-001", "t-20260710-002"],
    decisionGroups: [{ meeting: "meetings/2026-07-10/Planning.md", taskIds: ["t-20260710-001", "t-20260710-002"], taskTitles: ["Choose launch scope", "Name the implementation owner"] }],
  });
  assert.ok(counted.failures.some((failure) => failure.includes("pending count")), counted.failures.join(" | "));

  const echoed = validateBriefing(md.replace("Planning aligned the implementation path, but scope and ownership still block the next handoff.", "Planning aligned the path; package feedback for Derek on the drill-through branch."), "daily", {
    allowedDecisionTaskIds: ["t-20260710-001", "t-20260710-002"],
    decisionGroups: [{ meeting: "meetings/2026-07-10/Planning.md", taskIds: ["t-20260710-001", "t-20260710-002"], taskTitles: ["Package feedback for Derek on the drill-through branch before it can ship", "Name the implementation owner"] }],
  });
  assert.ok(echoed.failures.some((failure) => failure.includes("TaskCard title prose")), echoed.failures.join(" | "));

  const duplicatePill = validateBriefing(md.replace("Planning aligned the implementation path, but scope and ownership still block the next handoff.", "[Planning](<hilt:meeting/meetings/2026-07-10/Planning.md>) aligned the path, but ownership still blocks the handoff."), "daily", {
    allowedDecisionTaskIds: ["t-20260710-001", "t-20260710-002"],
    decisionGroups: [{ meeting: "meetings/2026-07-10/Planning.md", taskIds: ["t-20260710-001", "t-20260710-002"] }],
  });
  assert.ok(duplicatePill.failures.some((failure) => failure.includes("duplicate its citation")), duplicatePill.failures.join(" | "));
});

test("ordinary accepted task links outside Decisions are not treated as pending proposals", () => {
  const md = validDaily()
    .replace("- **Seb deep dive** due **6/30**.", "- [Seb deep dive](<hilt:task/t-20260707-029>) is due **6/30**.")
    .replace(
      "## 💼 Work & product",
      "## ⏭ Decisions awaiting you\n\n- Planning aligned the path; ownership still blocks the handoff.\n  - *meetings/2026-07-10/Planning.md, 2026-07-10*\n  - `t-20260710-001`\n\n## 💼 Work & product",
    );
  const result = validateBriefing(md, "daily", {
    allowedDecisionTaskIds: ["t-20260710-001"],
    decisionGroups: [{ meeting: "meetings/2026-07-10/Planning.md", taskIds: ["t-20260710-001"] }],
  });
  assert.equal(result.pass, true, result.failures.join(" | "));
});

test("native generation omits Decisions when no proposals and rejects duplicate queue prose", () => {
  const noQueue = validateBriefing(validDaily(), "daily", { allowedDecisionTaskIds: [], decisionGroups: [] });
  assert.equal(noQueue.pass, true, noQueue.failures.join(" | "));

  const duplicated = validDaily().replace("- EverPro reforecast is sales-coupled.", "- **4 pending verdicts** remain from meetings.");
  const result = validateBriefing(duplicated, "daily", { allowedDecisionTaskIds: [], decisionGroups: [] });
  assert.ok(result.failures.some((failure) => failure.includes("duplicates")), result.failures.join(" | "));

  const inventory = validDaily().replace("- EverPro reforecast is sales-coupled.", "- Meeting-actions holds 338 open entries and 3 escalated items.");
  const inventoryResult = validateBriefing(inventory, "daily", { allowedDecisionTaskIds: [], decisionGroups: [] });
  assert.ok(inventoryResult.failures.some((failure) => failure.includes("duplicates")), inventoryResult.failures.join(" | "));
});

test("weekend Decisions sits between Closed/open loops and Work", () => {
  const md = validWeekend()
    .replace("## 📚 Library & knowledge", "## ✅ Closed loops / open loops\n- Weekly closure.\n\n## ⏭ Decisions awaiting you\n\n- Planning converged on the direction; the remaining scope call controls next week's sequence.\n  - *meetings/2026-07-10/Planning.md, 2026-07-10*\n  - `t-20260710-001`\n\n## 💼 Work & product\n- Weekly movement.\n\n## 📚 Library & knowledge");
  const result = validateBriefing(md, "weekend", {
    allowedDecisionTaskIds: ["t-20260710-001"],
    decisionGroups: [{ meeting: "meetings/2026-07-10/Planning.md", taskIds: ["t-20260710-001"] }],
  });
  assert.equal(result.pass, true, result.failures.join(" | "));
});

// ── B5 pill citations: citation-only sub-bullets are a SOFT warning, never a failure ────────

test("a citation-only sub-bullet warns but never fails", () => {
  const md = validDaily().replace(
    "  - Threads to last week's flagged risk. *git: everpro, 6/25*",
    "  - Threads to last week's flagged risk.\n  - *meetings/2026-06-25/EverPro sync-2026-06-25.md, 2026-06-25*",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, true, `must stay soft — unexpected failures: ${r.failures.join(" | ")}`);
  assert.ok(r.warnings.some((w) => w.includes("citation-only")), r.warnings.join(" | "));
});

test("evidence sub-bullets with trailing citations do NOT warn", () => {
  // validDaily()'s sub-bullets all carry real prose before their citations.
  const r = validateBriefing(validDaily(), "daily");
  assert.ok(!r.warnings.some((w) => w.includes("citation-only")), r.warnings.join(" | "));
});

test("the ⏭ meeting-citation sub-bullet is exempt (load-bearing join key, not reading material)", () => {
  const md = validDaily().replace(
    "## 💼 Work & product",
    "## ⏭ Next steps\n- **OC planning (6/30)** — Phase 2 verbally approved\n  - *meetings/2026-06-30/OC planning-2026-06-30.md, 2026-06-30*\n  - `t-20260707-001`\n\n## 💼 Work & product",
  );
  const r = validateBriefing(md, "daily");
  assert.equal(r.pass, true, `unexpected failures: ${r.failures.join(" | ")}`);
  assert.ok(!r.warnings.some((w) => w.includes("citation-only")), r.warnings.join(" | "));
});

test("out-of-order sections fail", () => {
  const md = validDaily().replace("## 📈 System", "## 📅 System"); // a second 📅 after 📚 → order break
  const r = validateBriefing(md, "daily");
  assert.ok(r.failures.some((f) => f.includes("order")), r.failures.join(" | "));
});

test("too-thin daily fails the length floor", () => {
  const tiny = `# Morning Briefing — Friday, June 26, 2026\n\n## 📅 Today\n- thin ${REPORT}\n${FOOTER}`;
  const r = validateBriefing(tiny, "daily");
  assert.ok(r.failures.some((f) => f.includes("too short")));
});

test("weekend requires frontmatter with the required keys", () => {
  const noFm = `# Weekend Briefing — Jun 20-21, 2026\n\n## 🧭 Direction of travel\n- x\n  - ${REPORT}\n${FOOTER}`;
  const r = validateBriefing(noFm, "weekend");
  assert.ok(r.failures.some((f) => f.includes("frontmatter")));
});

test("a valid weekend (frontmatter + sections + links + footer) passes", () => {
  const r = validateBriefing(validWeekend(), "weekend");
  assert.equal(r.pass, true, `unexpected failures: ${r.failures.join(" | ")}`);
});

test("structured weekend requires and accepts the exact Saturday memo module", () => {
  const lead = "This weekend's recommendations converge on one practical tension: agents can accelerate delivery only when their work remains legible to the people accountable for it. The set makes that tradeoff concrete across operating models, evaluation, and reviewable artifacts rather than treating automation as an end in itself.";
  const md = validWeekend().replace(
    `- Thematic substance.\n  - ${REPORT}`,
    `### Recommended for you
${lead}

${EPISODES.map((id) => `- \`rec:${id}\``).join("\n")}

### Editor's memo
**The week in reviewable agent work**

The memo connects this week's strongest sources to the operating decisions now in motion.

[Read the memo](/api/reports/memo)

### Library health
${HEALTH}

${DAILY_REPORT}`,
  );
  const result = validateBriefing(md, "weekend", {
    allowedRecommendationEpisodeIds: EPISODES,
    libraryReportAvailable: true,
    libraryHealthSummary: HEALTH,
    libraryMemoExpected: true,
  });
  assert.equal(result.pass, true, result.failures.join(" | "));

  const missingMemo = validateBriefing(md.replace(/### Editor's memo[\s\S]*?(?=### Library health)/, ""), "weekend", {
    allowedRecommendationEpisodeIds: EPISODES,
    libraryReportAvailable: true,
    libraryHealthSummary: HEALTH,
    libraryMemoExpected: true,
  });
  assert.ok(missingMemo.failures.some((failure) => failure.includes("omitted")));
});
